using System.ComponentModel.DataAnnotations;

namespace NtisPlatform.Application.DTOs.Master.UserMaster;

// READ DTO

public class UserDto : BaseDtos
{
    public string UserName { get; set; } = null!;
    public string? FirstName { get; set; }
    public string? MiddleName { get; set; }
    public string? LastName { get; set; }
    public string? UserCode { get; set; }
    public string? Address { get; set; }
    public string? MobileNo { get; set; }
    public string? AlternateMobileNo { get; set; }
    public string? Email { get; set; }
    public bool MustChangePassword { get; set; }
    public string? Language { get; set; }
    public string? Remark { get; set; }
    public int? EmployeeTypeID { get; set; }
    public List<UserDepartmentAllocationDto>? Departments { get; set; }
    public List<UserModuleAllocationDto>? ModuleAccess { get; set; }
    public List<UserRoleAllocationDto>? RoleAllocations { get; set; }
}

// CREATE DTO
// Password is NOT accepted from the client — auto-generated by the service.
// MustChangePassword is always forced true on creation.

public class CreateUserDto : CreateBaseDtos
{
    [Required(ErrorMessage = "UserName_Required")]
    [StringLength(100, ErrorMessage = "UserName_MaxLen_100")]
    public string UserName { get; set; } = null!;

    [StringLength(100, ErrorMessage = "FirstName_MaxLen_100")]
    public string? FirstName { get; set; }

    [StringLength(100, ErrorMessage = "MiddleName_MaxLen_100")]
    public string? MiddleName { get; set; }

    [StringLength(100, ErrorMessage = "LastName_MaxLen_100")]
    public string? LastName { get; set; }

    [StringLength(50, ErrorMessage = "UserCode_MaxLen_50")]
    public string? UserCode { get; set; }

    [StringLength(400, ErrorMessage = "Address_MaxLen_400")]
    public string? Address { get; set; }

    [StringLength(30, ErrorMessage = "MobileNo_MaxLen_30")]
    public string? MobileNo { get; set; }

    [StringLength(30, ErrorMessage = "AlternateMobileNo_MaxLen_30")]
    public string? AlternateMobileNo { get; set; }

    [EmailAddress(ErrorMessage = "Email_Invalid")]
    [StringLength(100, ErrorMessage = "Email_MaxLen_100")]
    public string? Email { get; set; }

    public int? EmployeeTypeID { get; set; }

    [StringLength(10, ErrorMessage = "Language_MaxLen_10")]
    public string? Language { get; set; }

    [StringLength(400, ErrorMessage = "Remark_MaxLen_400")]
    public string? Remark { get; set; }

    public List<UserDepartmentAllocationCreateDto>? Departments { get; set; }
    public List<UserModuleAllocationCreateDto>? ModuleAccess { get; set; }
    public List<UserRoleAllocationCreateDto>? RoleAllocations { get; set; }
}

// UPDATE DTO — profile fields only
// IsActive excluded — use Activate / Deactivate endpoints.
// MustChangePassword excluded — controlled only through password reset flow.

public class UpdateUserDto : UpdateBaseDtos
{
    [Required(ErrorMessage = "UserName_Required")]
    [StringLength(100, ErrorMessage = "UserName_MaxLen_100")]
    public string UserName { get; set; } = null!;

    [StringLength(100, ErrorMessage = "FirstName_MaxLen_100")]
    public string? FirstName { get; set; }

    [StringLength(100, ErrorMessage = "MiddleName_MaxLen_100")]
    public string? MiddleName { get; set; }

    [StringLength(100, ErrorMessage = "LastName_MaxLen_100")]
    public string? LastName { get; set; }

    [StringLength(50, ErrorMessage = "UserCode_MaxLen_50")]
    public string? UserCode { get; set; }

    [StringLength(400, ErrorMessage = "Address_MaxLen_400")]
    public string? Address { get; set; }

    [StringLength(30, ErrorMessage = "MobileNo_MaxLen_30")]
    public string? MobileNo { get; set; }

    [StringLength(30, ErrorMessage = "AlternateMobileNo_MaxLen_30")]
    public string? AlternateMobileNo { get; set; }

    [EmailAddress(ErrorMessage = "Email_Invalid")]
    [StringLength(100, ErrorMessage = "Email_MaxLen_100")]
    public string? Email { get; set; }

    public int? EmployeeTypeID { get; set; }

    [StringLength(10, ErrorMessage = "Language_MaxLen_10")]
    public string? Language { get; set; }

    [StringLength(400, ErrorMessage = "Remark_MaxLen_400")]
    public string? Remark { get; set; }

    public List<UserDepartmentAllocationCreateDto>? Departments { get; set; }
    public List<UserModuleAllocationCreateDto>? ModuleAccess { get; set; }
    public List<UserRoleAllocationCreateDto>? RoleAllocations { get; set; }
}

// SECURITY ADMIN COMMANDS

// DELETE /users/{id}
// Requires UpdatedBy to track who performed the deletion in allocation history
public class DeleteUserDto : UpdateBaseDtos { }

// PUT /users/{id}/deactivate
public class DeactivateUserDto : UpdateBaseDtos { }

// PUT /users/{id}/activate
public class ActivateUserDto : UpdateBaseDtos { }

// PUT /users/{id}/reset-password
// System auto-generates a new password — nothing accepted from or returned to the client.
// MustChangePassword always forced true.
public class ResetPasswordDto : UpdateBaseDtos { }

// Returned by activate / deactivate / reset-password
public class UserSecurityStatusDto
{
    public int Id { get; set; }
    public string UserName { get; set; } = null!;
    public bool IsActive { get; set; }
    public bool MustChangePassword { get; set; }
    public DateTime? UpdatedDate { get; set; }
}