using AutoMapper;
using NtisPlatform.Application.DTOs.Property.ApartmentQC;
using NtisPlatform.Core.Entities;

namespace NtisPlatform.Application.Mappings;

/// <summary>
/// AutoMapper profile for Apartment QC DTO conversions and comparison difference calculations.
/// </summary>
public class ApartmentQCMappingProfile : Profile
{
    public ApartmentQCMappingProfile()
    {
        // ── Map NewSurveyMappingInput -> PropertyApartmentTaxDto (Per Unit / Detail Level) ─────
        CreateMap<NewSurveyMappingInput, PropertyApartmentTaxDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Property.Id))
            .ForMember(dest => dest.PDNId, opt => opt.MapFrom(src => src.Detail != null ? (long?)src.Detail.Id : null))
            .ForMember(dest => dest.TaxZoneId, opt => opt.MapFrom(src => src.Property.TaxZoneId))
            .ForMember(dest => dest.ZoneNo, opt => opt.MapFrom(src => src.ZoneNo))
            .ForMember(dest => dest.PropertyNo, opt => opt.MapFrom(src => src.Property.PropertyNo))
            .ForMember(dest => dest.OldPropertyNo, opt => opt.MapFrom(src => src.OldProperty != null ? src.OldProperty.OldPropertyNo : null))
            .ForMember(dest => dest.WardId, opt => opt.MapFrom(src => src.Property.WardId))
            .ForMember(dest => dest.WardNo, opt => opt.MapFrom(src => src.WardNo))
            .ForMember(dest => dest.MobileNo, opt => opt.MapFrom(src => src.Property.MobileNo))
            .ForMember(dest => dest.EmailId, opt => opt.MapFrom(src => src.Property.EmailId))
            .ForMember(dest => dest.OCNo, opt => opt.Ignore())
            .ForMember(dest => dest.FlatOrShopNo, opt => opt.MapFrom(src => src.Property.FlatOrShopNo))
            .ForMember(dest => dest.FlatOrShopName, opt => opt.MapFrom(src => src.Property.FlatOrShopName))
            .ForMember(dest => dest.FlatOrShopNoEnglish, opt => opt.MapFrom(src => src.Property.FlatOrShopNoEnglish))
            .ForMember(dest => dest.FlatOrShopNameEnglish, opt => opt.MapFrom(src => src.Property.FlatOrShopNameEnglish))
            .ForMember(dest => dest.OwnerName, opt => opt.MapFrom(src => src.Property.OwnerName))
            .ForMember(dest => dest.OwnerNameEnglish, opt => opt.MapFrom(src => src.Property.OwnerNameEnglish))
            .ForMember(dest => dest.OccupierName, opt => opt.MapFrom(src => src.Property.OccupierName))
            .ForMember(dest => dest.OccupierNameEnglish, opt => opt.MapFrom(src => src.Property.OccupierNameEnglish))
            .ForMember(dest => dest.PropertyType, opt => opt.MapFrom(src => src.Property.PropertyType))
            .ForMember(dest => dest.PropertyTypeName, opt => opt.MapFrom(src => src.Property.PropertyTypeName))
            .ForMember(dest => dest.TypeOfUse, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.TypeOfUse : null))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.Type : null))
            .ForMember(dest => dest.ApartmentType, opt => opt.MapFrom(src => src.Property.ApartmentType))
            .ForMember(dest => dest.PartType, opt => opt.MapFrom(src => src.Property.PartType))
            .ForMember(dest => dest.BHK, opt => opt.MapFrom(src => src.Property.BHK))
            .ForMember(dest => dest.Wing, opt => opt.MapFrom(src => src.Property.Wing))
            .ForMember(dest => dest.WingDetailId, opt => opt.MapFrom(src => src.Property.WingDetailId))
            .ForMember(dest => dest.NoOfRooms, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.NoOfRooms : null))
            .ForMember(dest => dest.Floor, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.Floor : null))
            .ForMember(dest => dest.SubFloor, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.SubFloor : null))
            .ForMember(dest => dest.SubTypeOfUse, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.SubTypeOfUse : null))
            .ForMember(dest => dest.ConstructionYear, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.ConstructionYear : null))
            .ForMember(dest => dest.AssessmentYear, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.AssessmentYear : null))
            .ForMember(dest => dest.ConstructionType, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.ConstructionType : null))
            .ForMember(dest => dest.OldConstructionArea, opt => opt.MapFrom(src => src.OldProperty != null ? (decimal?)src.OldProperty.OldConstructionArea : null))
            .ForMember(dest => dest.OldConstructionYear, opt => opt.MapFrom(src => src.OldProperty != null ? src.OldProperty.OldConstructionYear : null))
            .ForMember(dest => dest.OldUseType, opt => opt.MapFrom(src => src.OldProperty != null ? src.OldProperty.OldUseType : null))
            .ForMember(dest => dest.OldConstructionType, opt => opt.Ignore())
            .ForMember(dest => dest.OldRV, opt => opt.MapFrom(src => src.OldProperty != null ? (decimal?)src.OldProperty.OldRV : null))
            .ForMember(dest => dest.OldTotalTax, opt => opt.MapFrom(src => src.OldProperty != null ? (decimal?)src.OldProperty.OldTotalTax : null))
            .ForMember(dest => dest.OldCSN, opt => opt.MapFrom(src => src.OldProperty != null ? src.OldProperty.OldCSN : null))
            .ForMember(dest => dest.CarpetASqMtr, opt => opt.MapFrom(src => src.Detail != null ? (decimal)(src.Detail.CarpetAreaSqMeter ?? 0) : 0m))
            .ForMember(dest => dest.CarpetASqFt, opt => opt.MapFrom(src => src.Detail != null ? (decimal)(src.Detail.CarpetAreaSqFeet ?? 0) : 0m))
            .ForMember(dest => dest.BuiltupASqMtr, opt => opt.MapFrom(src => src.Detail != null ? (decimal)(src.Detail.BuiltupAreaSqMeter ?? 0) : 0m))
            .ForMember(dest => dest.BuiltupASqFt, opt => opt.MapFrom(src => src.Detail != null ? (decimal)(src.Detail.BuiltupAreaSqFeet ?? 0) : 0m))
            .ForMember(dest => dest.RetroTaxTotal, opt => opt.MapFrom(src => src.RetroTaxTotal > 0 ? src.RetroTaxTotal : null))
            .ForMember(dest => dest.RateableValue, opt => opt.MapFrom(src => src.RateableValue))
            .ForMember(dest => dest.CapitalValue, opt => opt.MapFrom(src => src.CapitalValue))
            .ForMember(dest => dest.CalculationValue, opt => opt.MapFrom(src => src.CalculationValue))
            .ForMember(dest => dest.NewTaxTotal, opt => opt.MapFrom(src => src.NewTaxTotal))
            .ForMember(dest => dest.NewTaxTotalRV, opt => opt.MapFrom(src => src.NewTaxTotalRV))
            .ForMember(dest => dest.NewTaxTotalCV, opt => opt.MapFrom(src => src.NewTaxTotalCV))
            .ForMember(dest => dest.CurrentDemand, opt => opt.MapFrom(src => src.CurrentDemand ?? (src.NewTaxTotal > 0 ? (decimal?)src.NewTaxTotal : null)))
            .ForMember(dest => dest.Photos, opt => opt.MapFrom(src => src.Photos ?? new List<PropertyPhotoDocumentDto>()))
            .ForMember(dest => dest.PropertyPhotoDocumentGuid, opt => opt.MapFrom(src => src.Photos != null ? src.Photos.FirstOrDefault(p => string.Equals(p.PhotoTypeCode, "PROPERTY_PHOTO", StringComparison.OrdinalIgnoreCase)) != null ? src.Photos.FirstOrDefault(p => string.Equals(p.PhotoTypeCode, "PROPERTY_PHOTO", StringComparison.OrdinalIgnoreCase))!.DocumentGuid : (Guid?)null : (Guid?)null))
            .ForMember(dest => dest.PlanPhotoDocumentGuid, opt => opt.MapFrom(src => src.Photos != null ? src.Photos.FirstOrDefault(p => string.Equals(p.PhotoTypeCode, "PLAN_PHOTO", StringComparison.OrdinalIgnoreCase)) != null ? src.Photos.FirstOrDefault(p => string.Equals(p.PhotoTypeCode, "PLAN_PHOTO", StringComparison.OrdinalIgnoreCase))!.DocumentGuid : (Guid?)null : (Guid?)null));

        // ── Map PropertyMastOldEntity -> PropertyApartmentTaxDto (Old Survey) ─────
        CreateMap<PropertyMastOldEntity, PropertyApartmentTaxDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.PropertyNo, opt => opt.MapFrom(src => src.OldPropertyNo ?? string.Empty))
            .ForMember(dest => dest.OldPropertyNo, opt => opt.MapFrom(src => src.OldPropertyNo))
            .ForMember(dest => dest.WardNo, opt => opt.MapFrom(src => src.OldWardNo))
            .ForMember(dest => dest.ZoneNo, opt => opt.MapFrom(src => src.OldZoneNo))
            .ForMember(dest => dest.MobileNo, opt => opt.MapFrom(src => src.OldMobileNo))
            .ForMember(dest => dest.EmailId, opt => opt.MapFrom(src => src.OldEmailId))
            .ForMember(dest => dest.OCNo, opt => opt.Ignore())
            .ForMember(dest => dest.FlatOrShopNo, opt => opt.MapFrom(src => src.OldFlatOrShopNumber))
            .ForMember(dest => dest.OwnerName, opt => opt.MapFrom(src => src.OldOwnerName))
            .ForMember(dest => dest.OwnerNameEnglish, opt => opt.MapFrom(src => src.OldOwnerNameEnglish))
            .ForMember(dest => dest.OccupierName, opt => opt.MapFrom(src => src.OldOccupierName))
            .ForMember(dest => dest.OccupierNameEnglish, opt => opt.MapFrom(src => src.OldOccupierNameEnglish))
            .ForMember(dest => dest.Floor, opt => opt.MapFrom(src => src.OldFloor))
            .ForMember(dest => dest.ConstructionYear, opt => opt.MapFrom(src => src.OldConstructionYear))
            .ForMember(dest => dest.TypeOfUse, opt => opt.MapFrom(src => src.OldUseType))
            .ForMember(dest => dest.OldConstructionType, opt => opt.MapFrom(src => src.OldConstructionTypeOfUseId))
            .ForMember(dest => dest.OldRV, opt => opt.MapFrom(src => (decimal?)src.OldRV))
            .ForMember(dest => dest.OldTotalTax, opt => opt.MapFrom(src => (decimal?)src.OldTotalTax))
            .ForMember(dest => dest.OldCSN, opt => opt.MapFrom(src => src.OldCSN))
            .ForMember(dest => dest.BuiltupASqMtr, opt => opt.MapFrom(src => (decimal)(src.OldConstructionArea ?? 0)))
            .ForMember(dest => dest.BuiltupASqFt, opt => opt.MapFrom(src => (decimal)((src.OldConstructionArea ?? 0) * 10.7639)))
            .ForMember(dest => dest.NoOfRooms, opt => opt.MapFrom(src => src.OldTotalRooms))
            .ForMember(dest => dest.Wing, opt => opt.MapFrom(src => src.OldWing))
            .ForMember(dest => dest.CurrentDemand, opt => opt.Ignore());

        // ── Map NewSurveyMappingInput -> NewSurveyPropertyDto (Dedicated New Survey DTO) ─────
        CreateMap<NewSurveyMappingInput, NewSurveyPropertyDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Property.Id))
            .ForMember(dest => dest.PDNId, opt => opt.MapFrom(src => src.Detail != null ? (long?)src.Detail.Id : null))
            .ForMember(dest => dest.TaxZoneId, opt => opt.MapFrom(src => src.Property.TaxZoneId))
            .ForMember(dest => dest.ZoneNo, opt => opt.MapFrom(src => src.ZoneNo))
            .ForMember(dest => dest.PropertyNo, opt => opt.MapFrom(src => src.Property.PropertyNo))
            .ForMember(dest => dest.WardId, opt => opt.MapFrom(src => src.Property.WardId))
            .ForMember(dest => dest.WardNo, opt => opt.MapFrom(src => src.WardNo))
            .ForMember(dest => dest.MobileNo, opt => opt.MapFrom(src => src.Property.MobileNo))
            .ForMember(dest => dest.EmailId, opt => opt.MapFrom(src => src.Property.EmailId))
            .ForMember(dest => dest.OCNo, opt => opt.Ignore())
            .ForMember(dest => dest.OCDate, opt => opt.Ignore())
            .ForMember(dest => dest.FlatOrShopNo, opt => opt.MapFrom(src => src.Property.FlatOrShopNo))
            .ForMember(dest => dest.FlatOrShopName, opt => opt.MapFrom(src => src.Property.FlatOrShopName))
            .ForMember(dest => dest.FlatOrShopNoEnglish, opt => opt.MapFrom(src => src.Property.FlatOrShopNoEnglish))
            .ForMember(dest => dest.FlatOrShopNameEnglish, opt => opt.MapFrom(src => src.Property.FlatOrShopNameEnglish))
            .ForMember(dest => dest.OwnerName, opt => opt.MapFrom(src => src.Property.OwnerName))
            .ForMember(dest => dest.OwnerNameEnglish, opt => opt.MapFrom(src => src.Property.OwnerNameEnglish))
            .ForMember(dest => dest.OccupierName, opt => opt.MapFrom(src => src.Property.OccupierName))
            .ForMember(dest => dest.OccupierNameEnglish, opt => opt.MapFrom(src => src.Property.OccupierNameEnglish))
            .ForMember(dest => dest.PropertyType, opt => opt.MapFrom(src => src.Property.PropertyType))
            .ForMember(dest => dest.PropertyTypeName, opt => opt.MapFrom(src => src.Property.PropertyTypeName))
            .ForMember(dest => dest.TypeOfUse, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.TypeOfUse : null))
            .ForMember(dest => dest.Type, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.Type : null))
            .ForMember(dest => dest.ApartmentType, opt => opt.MapFrom(src => src.Property.ApartmentType))
            .ForMember(dest => dest.PartType, opt => opt.MapFrom(src => src.Property.PartType))
            .ForMember(dest => dest.BHK, opt => opt.MapFrom(src => src.Property.BHK))
            .ForMember(dest => dest.Wing, opt => opt.MapFrom(src => src.Property.Wing))
            .ForMember(dest => dest.WingDetailId, opt => opt.MapFrom(src => src.Property.WingDetailId))
            .ForMember(dest => dest.NoOfRooms, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.NoOfRooms : null))
            .ForMember(dest => dest.Floor, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.Floor : null))
            .ForMember(dest => dest.SubFloor, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.SubFloor : null))
            .ForMember(dest => dest.SubTypeOfUse, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.SubTypeOfUse : null))
            .ForMember(dest => dest.ConstructionYear, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.ConstructionYear : null))
            .ForMember(dest => dest.AssessmentYear, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.AssessmentYear : null))
            .ForMember(dest => dest.ConstructionType, opt => opt.MapFrom(src => src.Detail != null ? src.Detail.ConstructionType : null))
            .ForMember(dest => dest.CarpetASqMtr, opt => opt.MapFrom(src => src.Detail != null ? (decimal)(src.Detail.CarpetAreaSqMeter ?? 0) : 0m))
            .ForMember(dest => dest.CarpetASqFt, opt => opt.MapFrom(src => src.Detail != null ? (decimal)(src.Detail.CarpetAreaSqFeet ?? 0) : 0m))
            .ForMember(dest => dest.BuiltupASqMtr, opt => opt.MapFrom(src => src.Detail != null ? (decimal)(src.Detail.BuiltupAreaSqMeter ?? 0) : 0m))
            .ForMember(dest => dest.BuiltupASqFt, opt => opt.MapFrom(src => src.Detail != null ? (decimal)(src.Detail.BuiltupAreaSqFeet ?? 0) : 0m))
            .ForMember(dest => dest.RetroTaxTotal, opt => opt.MapFrom(src => src.RetroTaxTotal > 0 ? src.RetroTaxTotal : null))
            .ForMember(dest => dest.RateableValue, opt => opt.MapFrom(src => src.RateableValue))
            .ForMember(dest => dest.CapitalValue, opt => opt.MapFrom(src => src.CapitalValue))
            .ForMember(dest => dest.CalculationValue, opt => opt.MapFrom(src => src.CalculationValue))
            .ForMember(dest => dest.NewTaxTotal, opt => opt.MapFrom(src => src.NewTaxTotal))
            .ForMember(dest => dest.NewTaxTotalRV, opt => opt.MapFrom(src => src.NewTaxTotalRV))
            .ForMember(dest => dest.NewTaxTotalCV, opt => opt.MapFrom(src => src.NewTaxTotalCV))
            .ForMember(dest => dest.CurrentDemand, opt => opt.MapFrom(src => src.CurrentDemand ?? (src.NewTaxTotal > 0 ? (decimal?)src.NewTaxTotal : null)))
            .ForMember(dest => dest.Photos, opt => opt.MapFrom(src => src.Photos ?? new List<PropertyPhotoDocumentDto>()))
            .ForMember(dest => dest.PropertyPhotoDocumentGuid, opt => opt.MapFrom(src => src.Photos != null ? src.Photos.FirstOrDefault(p => string.Equals(p.PhotoTypeCode, "PROPERTY_PHOTO", StringComparison.OrdinalIgnoreCase)) != null ? src.Photos.FirstOrDefault(p => string.Equals(p.PhotoTypeCode, "PROPERTY_PHOTO", StringComparison.OrdinalIgnoreCase))!.DocumentGuid : (Guid?)null : (Guid?)null))
            .ForMember(dest => dest.PlanPhotoDocumentGuid, opt => opt.MapFrom(src => src.Photos != null ? src.Photos.FirstOrDefault(p => string.Equals(p.PhotoTypeCode, "PLAN_PHOTO", StringComparison.OrdinalIgnoreCase)) != null ? src.Photos.FirstOrDefault(p => string.Equals(p.PhotoTypeCode, "PLAN_PHOTO", StringComparison.OrdinalIgnoreCase))!.DocumentGuid : (Guid?)null : (Guid?)null));

        // ── Map PropertyMastOldEntity -> OldSurveyPropertyDto (Dedicated Old Survey DTO) ─────
        CreateMap<PropertyMastOldEntity, OldSurveyPropertyDto>()
            .ForMember(dest => dest.Id, opt => opt.MapFrom(src => src.Id))
            .ForMember(dest => dest.PropertyNo, opt => opt.MapFrom(src => src.OldPropertyNo ?? string.Empty))
            .ForMember(dest => dest.OldPropertyNo, opt => opt.MapFrom(src => src.OldPropertyNo))
            .ForMember(dest => dest.WardNo, opt => opt.MapFrom(src => src.OldWardNo))
            .ForMember(dest => dest.ZoneNo, opt => opt.MapFrom(src => src.OldZoneNo))
            .ForMember(dest => dest.MobileNo, opt => opt.MapFrom(src => src.OldMobileNo))
            .ForMember(dest => dest.EmailId, opt => opt.MapFrom(src => src.OldEmailId))
            .ForMember(dest => dest.OCNo, opt => opt.Ignore())
            .ForMember(dest => dest.OCDate, opt => opt.Ignore())
            .ForMember(dest => dest.OldTaxDetails, opt => opt.Ignore())
            .ForMember(dest => dest.OldPropertyTypeId, opt => opt.MapFrom(src => src.OldPropertyTypeId))
            .ForMember(dest => dest.OldPartitionNo, opt => opt.MapFrom(src => src.OldPartitionNo))
            .ForMember(dest => dest.OldEgovNo, opt => opt.MapFrom(src => src.OldEgovNo))
            .ForMember(dest => dest.OldPlotNo, opt => opt.MapFrom(src => src.OldPlotNo))
            .ForMember(dest => dest.OldAssessmentYear, opt => opt.MapFrom(src => src.OldAssessmentYear))
            .ForMember(dest => dest.OldAssessmentDate, opt => opt.MapFrom(src => src.OldAssessmentDate))
            .ForMember(dest => dest.OldConstructionTypeOfUseId, opt => opt.MapFrom(src => src.OldConstructionTypeOfUseId))
            .ForMember(dest => dest.FlatOrShopNo, opt => opt.MapFrom(src => src.OldFlatOrShopNumber))
            .ForMember(dest => dest.FlatOrShopName, opt => opt.Ignore())
            .ForMember(dest => dest.OwnerName, opt => opt.MapFrom(src => src.OldOwnerName))
            .ForMember(dest => dest.OwnerNameEnglish, opt => opt.MapFrom(src => src.OldOwnerNameEnglish))
            .ForMember(dest => dest.OccupierName, opt => opt.MapFrom(src => src.OldOccupierName))
            .ForMember(dest => dest.OccupierNameEnglish, opt => opt.MapFrom(src => src.OldOccupierNameEnglish))
            .ForMember(dest => dest.Floor, opt => opt.MapFrom(src => src.OldFloor))
            .ForMember(dest => dest.Wing, opt => opt.MapFrom(src => src.OldWing))
            .ForMember(dest => dest.NoOfRooms, opt => opt.MapFrom(src => src.OldTotalRooms))
            .ForMember(dest => dest.ConstructionYear, opt => opt.MapFrom(src => src.OldConstructionYear))
            .ForMember(dest => dest.TypeOfUse, opt => opt.MapFrom(src => src.OldUseType))
            .ForMember(dest => dest.ConstructionType, opt => opt.MapFrom(src => src.OldConstructionTypeOfUseId))
            .ForMember(dest => dest.RateableValue, opt => opt.MapFrom(src => (decimal?)src.OldRV))
            .ForMember(dest => dest.CapitalValue, opt => opt.Ignore())
            .ForMember(dest => dest.TotalTax, opt => opt.MapFrom(src => (decimal?)src.OldTotalTax))
            .ForMember(dest => dest.RetroTaxTotal, opt => opt.Ignore())
            .ForMember(dest => dest.CSN, opt => opt.MapFrom(src => src.OldCSN))
            .ForMember(dest => dest.ConstructionArea, opt => opt.MapFrom(src => (decimal?)src.OldConstructionArea))
            .ForMember(dest => dest.CarpetASqMtr, opt => opt.Ignore())
            .ForMember(dest => dest.CarpetASqFt, opt => opt.Ignore())
            .ForMember(dest => dest.BuiltupASqMtr, opt => opt.MapFrom(src => (decimal)(src.OldConstructionArea ?? 0)))
            .ForMember(dest => dest.BuiltupASqFt, opt => opt.MapFrom(src => (decimal)((src.OldConstructionArea ?? 0) * 10.7639)))
            .ForMember(dest => dest.Photos, opt => opt.Ignore())
            .ForMember(dest => dest.PropertyPhotoDocumentGuid, opt => opt.Ignore())
            .ForMember(dest => dest.PlanPhotoDocumentGuid, opt => opt.Ignore());

        // ── Map (NewSurveyPropertyDto, OldSurveyPropertyDto) Tuple -> ApartmentQCPropertyDifferenceDto ─────
        CreateMap<(NewSurveyPropertyDto NewSurvey, OldSurveyPropertyDto OldSurvey), ApartmentQCPropertyDifferenceDto>()
            .ForMember(dest => dest.CarpetAreaSqMeterDiff, opt => opt.MapFrom(src => (src.NewSurvey.CarpetASqMtr ?? 0m) - (src.OldSurvey.CarpetASqMtr ?? 0m)))
            .ForMember(dest => dest.CarpetAreaSqFeetDiff, opt => opt.MapFrom(src => (src.NewSurvey.CarpetASqFt ?? 0m) - (src.OldSurvey.CarpetASqFt ?? 0m)))
            .ForMember(dest => dest.BuiltupAreaSqMeterDiff, opt => opt.MapFrom(src => (src.NewSurvey.BuiltupASqMtr ?? 0m) - (src.OldSurvey.BuiltupASqMtr ?? 0m)))
            .ForMember(dest => dest.BuiltupAreaSqFeetDiff, opt => opt.MapFrom(src => (src.NewSurvey.BuiltupASqFt ?? 0m) - (src.OldSurvey.BuiltupASqFt ?? 0m)))
            .ForMember(dest => dest.RateableValueDiff, opt => opt.MapFrom(src => (src.NewSurvey.RateableValue ?? 0m) - (src.OldSurvey.RateableValue ?? 0m)))
            .ForMember(dest => dest.CapitalValueDiff, opt => opt.MapFrom(src => src.NewSurvey.CapitalValue != null ? src.NewSurvey.CapitalValue - (src.OldSurvey.CapitalValue ?? 0m) : (decimal?)null))
            .ForMember(dest => dest.TotalTaxDiff, opt => opt.MapFrom(src => src.NewSurvey.NewTaxTotal - (src.OldSurvey.TotalTax ?? 0m)))
            .ForMember(dest => dest.RetroTaxDiff, opt => opt.MapFrom(src => (src.NewSurvey.RetroTaxTotal ?? 0m) - (src.OldSurvey.RetroTaxTotal ?? 0m)));
    }
}
