using AutoMapper;
using NtisPlatform.Application.DTOs.Property;
using NtisPlatform.Core.Entities;

namespace NtisPlatform.Application.Mappings;

/// <summary>
/// Global Property Mapping Profile
/// Maps PropertyEntity to PropertyDto with all PropertyMast fields
/// </summary>
public class PropertyMappingProfile : Profile
{
    public PropertyMappingProfile()
    {
        // Entity to read-only DTO mapping
        CreateMap<PropertyEntity, PropertyDto>();

        // CreateDto to Entity
        CreateMap<CreatePropertyDto, PropertyEntity>()
            .ForMember(dest => dest.PropertyId, opt => opt.Ignore()) // Auto-generated by database
            .ForMember(dest => dest.CreatedDate, opt => opt.Ignore()) // Managed by Repository (BaseEntity handling)
            .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore()) // Managed by Repository on update
            .ForMember(dest => dest.CreatedBy, opt => opt.MapFrom(src => src.CreatedBy));

        // UpdateDto to Entity
        CreateMap<UpdatePropertyDto, PropertyEntity>()
            .ForMember(dest => dest.PropertyId, opt => opt.Ignore()) // Cannot change primary key
            .ForMember(dest => dest.CreatedDate, opt => opt.Ignore()) // Immutable - set on creation
            .ForMember(dest => dest.UpdatedDate, opt => opt.Ignore()) // Updated by Repository
            .ForMember(dest => dest.UpdatedBy, opt => opt.MapFrom(src => src.UpdatedBy));
    }
}
