<Project Sdk="Microsoft.NET.Sdk.Web">

  <!-- All common properties are inherited from Directory.Build.props -->

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="1.6.23" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Application\NtisPlatform.Application\NtisPlatform.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\NtisPlatform.Infrastructure\NtisPlatform.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Helpers\" />
    <Folder Include="Models\" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Templates\Emails\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
    <None Update="Certificates\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

</Project>
