namespace NtisPlatform.Application.Models;

/// <summary>
/// Represents a single localization entry for batch operations.
/// Key format: {Resource}_{GUID}_{PropertyName}
/// </summary>
public class LocalizationEntry
{
    public string Resource { get; set; } = string.Empty;

    /// <summary>
    /// Fully-formed localization key: {Resource}_{GUID}_{PropertyName}.
    /// Generated by the LocalizationProcessor and reused across updates for the same property.
    /// </summary>
    public string Key { get; set; } = string.Empty;

    public string PropertyName { get; set; } = string.Empty;
    public string Value { get; set; } = string.Empty;
    public string Language { get; set; } = "en";
}
