using System.ComponentModel.DataAnnotations;

namespace NtisPlatform.Application.DTOs.RuleEngine
{
    /// <summary>
    /// DTO for creating a new rule engine configuration
    /// </summary>
    public class CreateRuleEngineDto : CreateBaseDtos
    {
        [StringLength(50, ErrorMessage = "Rule code cannot exceed 50 characters")]
        public string? RuleCode { get; set; }

        [Required(ErrorMessage = "Rule name is required")]
        [StringLength(200, ErrorMessage = "Rule name cannot exceed 200 characters")]
        public string RuleName { get; set; } = string.Empty;

        [StringLength(1000, ErrorMessage = "Description cannot exceed 1000 characters")]
        public string? Description { get; set; }

        [StringLength(100, ErrorMessage = "Rule category cannot exceed 100 characters")]
        public string? RuleCategory { get; set; }

        /// <summary>Generated by backend from conditionsJson + effectJson. Not required from frontend.</summary>
        public string? RuleJson { get; set; }

        /// <summary>Serialized ConditionGroupState for UI re-hydration on edit</summary>
        public string? ConditionsJson { get; set; }

        /// <summary>Serialized EffectState for UI re-hydration on edit</summary>
        public string? EffectJson { get; set; }

        /// <summary>Serialized TargetFilterState for UI re-hydration on edit</summary>
        public string? TargetFiltersJson { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Priority must be greater than 0")]
        public int Priority { get; set; } = 100;

        public bool IsEnabled { get; set; } = true;

        /// <summary>When true, stops processing all remaining rules after this rule is applied</summary>
        public bool StopProcessing { get; set; } = false;

        /// <summary>
        /// List of rule IDs that should be skipped when this rule is applied.
        /// When this rule matches, these rules will be excluded from execution.
        /// </summary>
        public List<int> SkipRuleIds { get; set; } = new();

        /// <summary>
        /// Optional reason for each rule exclusion.
        /// If provided, will be stored with the exclusion record.
        /// </summary>
        public string? ExclusionReason { get; set; }

        [StringLength(500, ErrorMessage = "Change reason cannot exceed 500 characters")]
        public string? ChangeReason { get; set; }
    }
}

