using NtisPlatform.Application.DTOs;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace NtisPlatform.Application.DTOs.Rules.RuleEngine
{
    /// <summary>
    /// DTO for updating an existing rule engine configuration
    /// </summary>
    [JsonConverter(typeof(UpdateRuleEngineDtoJsonConverter))]
    public class UpdateRuleEngineDto : UpdateBaseDtos
    {
        [Required(ErrorMessage = "Rule name is required")]
        [StringLength(200, ErrorMessage = "Rule name cannot exceed 200 characters")]
        public string RuleName { get; set; } = string.Empty;

        [StringLength(1000, ErrorMessage = "Description cannot exceed 1000 characters")]
        public string? Description { get; set; }

        [StringLength(100, ErrorMessage = "Rule category cannot exceed 100 characters")]
        public string? RuleCategory { get; set; }

        /// <summary>Generated by backend from conditionsJson + effectJson. Not required from frontend.</summary>
        public string? RuleJson { get; set; }

        /// <summary>Serialized ConditionGroupState for UI re-hydration on edit</summary>
        public string? ConditionsJson { get; set; }

        /// <summary>Serialized EffectState for UI re-hydration on edit</summary>
        public string? EffectJson { get; set; }

        /// <summary>Serialized TargetFilterState for UI re-hydration on edit</summary>
        public string? TargetFiltersJson { get; set; }

        [Range(1, int.MaxValue, ErrorMessage = "Priority must be greater than 0")]
        public int Priority { get; set; } = 100;

        public bool IsEnabled { get; set; } = true;

        /// <summary>When true, stops processing all remaining rules after this rule is applied</summary>
        public bool StopProcessing { get; set; } = false;

        /// <summary>
        /// Optional FK to PTIS.RuleScopeMaster.
        /// Defines the scope/context this rule applies to. Null = all scopes.
        /// </summary>
        public int? RuleScopeId { get; set; }

        /// <summary>
        /// Optional FK to PTIS.PropertyRuleEvaluationMaster.
        /// Defines the parameter targeted by this rule (e.g. Rate, Rent, Maintenance).
        /// </summary>
        [Range(1, int.MaxValue, ErrorMessage = "PropertyRuleEvaluationMasterId must be greater than 0")]
        public int? PropertyRuleEvaluationMasterId { get; set; }

        [StringLength(500, ErrorMessage = "Change reason cannot exceed 500 characters")]
        public string? ChangeReason { get; set; }
    }
}
